version: 2.1

jobs:
  run_tests:
    docker: 
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run:
          name: "Install Dependencies"
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run: 
          name: "Run Test"
          command: |
            yarn test:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_and_test:
    jobs:
      - run_tests

